language: perl
sudo: required

perl:
  - "5.30"
  - "5.28"
  env:
    - TEST_ONLINE=mysql://root:travis@/mojolicious
  before_script:
    - sudo mysql -e "SET Password=PASSWORD('travis')"
    - sudo mysql -e 'create database mojolicious;'

env:
  global:
    - HARNESS_OPTIONS=j9
    - LC_ALL=C
  matrix:
    TEST_ONLINE=mysql://root@/mojolicious

matrix:
  include:
    - perl:
        - "5.20"
        - "5.18"
      dist: trusty
      env:
        - TEST_ONLINE=mysql://root@/mojolicious
      before_script:
        - mysql -e 'create database mojolicious;'

addons:
  mariadb: 10.4
  postgresql: 9.6
services:
  - postgresql
install:
  - cpanm -n Test::Pod Test::Pod::Coverage
  - cpanm -n Devel::CheckLib DBI DBD::mysql Mojo::mysql Mojo::Pg
  - cpanm -n --installdeps .
script:
  - prove -lvr t
notifications:
  email: false
