dist: xenial
language: perl
sudo: required

matrix:
  include:
#    - perl: "5.30"
#    - perl: "5.28"
#    - perl: "5.26"
#    - perl: "5.24"
#    - perl: "5.22"
    - perl: "5.20"
      dist: trusty
      env:
        - TEST_ONLINE=mysql://root@/mojolicious
      script:
        - mysql -e 'create database mojolicious;'

addons:
  mariadb: 10.4
  postgresql: 9.6
services:
  - postgresql
#before_script:
#  - mysql -e "SET Password=PASSWORD('travis')"
#  - mysql -e 'create database mojolicious;'
env:
  global:
    - HARNESS_OPTIONS=j9
    - LC_ALL=C
#    - TEST_ONLINE=mysql://root:travis@localhost/mojolicious
install:
  - cpanm -n Test::Pod Test::Pod::Coverage
  - cpanm -n Devel::CheckLib DBI DBD::mysql Mojo::mysql Mojo::Pg
  - cpanm -n --installdeps .
script:
  - prove -lvr t
notifications:
  email: false
