language: perl
sudo: required

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

before_script:
  - sudo mysql -e "SET Password=PASSWORD('travis')"
  - sudo mysql -e 'create database mojolicious default character set utf8 default collate utf8_general_ci;'

matrix:
  include:
    - perl: "5.20"
      dist: trusty
      before_script:
        - mysql -e 'create database mojolicious default character set utf8 default collate utf8_general_ci;'
      env:
        - TEST_ONLINE=mysql://root@/mojolicious
    - perl: "5.18"
      dist: trusty
      before_script:
        - mysql -e 'create database mojolicious default character set utf8 default collate utf8_general_ci;'
      env:
        - TEST_ONLINE=mysql://root@/mojolicious
    - perl: "5.16"
      dist: trusty
      before_script:
        - mysql -e 'create database mojolicious default character set utf8 default collate utf8_general_ci;'
      env:
        - TEST_ONLINE=mysql://root@/mojolicious
    - perl: "5.14"
      dist: trusty
      before_script:
        - mysql -e 'create database mojolicious default character set utf8 default collate utf8_general_ci;'
      env:
        - TEST_ONLINE=mysql://root@/mojolicious
    - perl: "5.12"
      dist: trusty
      before_script:
        - mysql -e 'create database mojolicious default character set utf8 default collate utf8_general_ci;'
      env:
        - TEST_ONLINE=mysql://root@/mojolicious
    - perl: "5.10"
      dist: trusty
      before_script:
        - mysql -e 'create database mojolicious default character set utf8 default collate utf8_general_ci;'
      env:
        - TEST_ONLINE=mysql://root@/mojolicious

env:
  global:
    - HARNESS_OPTIONS=j9
    - LC_ALL=C
    - TEST_ONLINE=mysql://root:travis@/mojolicious

addons:
  mariadb: 10.4

services:
  - postgresql
  - mariadb
install:
  - cpanm -n Test::Pod Test::Pod::Coverage
  - cpanm -n Devel::CheckLib DBI DBD::mysql Mojo::mysql Mojo::Pg
  - cpanm -n --installdeps .
script:
  - prove -lvr t
notifications:
  email: false
