name: linux
on: [push, pull_request]
jobs:
  perl:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mhf_test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mhf_test
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.18'
          - '5.24'
          - '5.30'
    container:
      image: perl:${{matrix.perl-version}}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          cpanm -n --installdeps . --with-all-features
          cpanm -n Test::Pod Test::Pod::Coverage
      - name: Run tests
        run: prove -l t/*.t
        env:
          HARNESS_OPTIONS: j3
          TEST_FOR: 500
          TEST_ONLINE_mysql: mysql://root:password@mysql:3306/mhf_test
          TEST_ONLINE_pg: postgresql://postgres:postgres@postgres:5432/mhf_test
          TEST_POD: 1
          TEST_PUBSUB: 1

