name: ci-ubuntu
on: [push, pull_request]
jobs:
  perl:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mojo_test
        ports:
          - 53306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.24'
          - '5.30'
    container:
      image: perl:${{matrix.perl-version}}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          cpanm -n --installdeps . --with-all-features
          cpanm -n Test::Pod Test::Pod::Coverage
      - name: Run tests
        run: prove -l t/*.t
        env:
          HARNESS_OPTIONS: j3
          TEST_FOR: 500

          TEST_ONLINE_mysql: mysql://root:password@127.0.0.1:53306/mojo_test
          TEST_ONLINE_pg: postgresql://postgres:postgres@postgres:5432/postgres
          TEST_POD: 1
          TEST_PUBSUB: 1

