name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'mhf_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"
      - name: Install dependencies
        run: |
          cpanm -n Cpanel::JSON::XS EV Role::Tiny
          cpanm -n Test::Pod Test::Pod::Coverage
          cpanm -n Devel::CheckLib DBI DBD::MariaDB Mojo::mysql Mojo::Pg
          cpanm -n --installdeps .
          psql -U postgres -c 'create database mhf_test'
          sudo mysql -e "SET Password=PASSWORD('travis')"
          sudo mysql -e 'create database mhf_test;'
      - name: Run tests
        run: prove -lvr t
        env:
          TEST_POD: 1
          TEST_EV: 1
          TEST_ONLINE_mariadb: mariadb://root:travis@/mhf_test
          TEST_ONLINE_pg: postgresql://postgres@/mhf_test
