name: ci-ubuntu
on: [push, pull_request]
jobs:
  perl:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.24'
          - '5.30'
    container:
      image: perl:${{matrix.perl-version}}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mariadb version: '10.4.10'
          mysql database: 'mhf_test'
          mysql root password: 'root'
          mysql user: 'mojolicious'
          mysql password: 'mojolicious'
      - name: Install dependencies
        run: |
          cpanm -n --installdeps . --with-all-features
          cpanm -n Test::Pod Test::Pod::Coverage
      - name: Run tests
        run: prove -l t/*.t
        env:
          HARNESS_OPTIONS: j3
          TEST_FOR: 500
          TEST_ONLINE_mysql: mysql://root@127.0.0.1:${{job.services.mysql.ports[3306]}}/mhf_test
          TEST_ONLINE_pg: postgresql://postgres:postgres@postgres:5432/postgres
          TEST_POD: 1
          TEST_PUBSUB: 1

